<a href="https://colab.research.google.com/github/bedryk-vedryk/ml-course/blob/main/LK_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [20]:
import numpy as np
v1 = np.random.rand(10)

print(v1)
print(v1.shape)

[0.76713817 0.61507787 0.78289585 0.80082988 0.16451576 0.91333379
 0.62784436 0.15480526 0.37667848 0.35248778]
(10,)


In [21]:
import random
v2 = np.array([random.uniform(0,1) for _ in range(10)])
print(v2)
print(v2.shape)

[0.09323109 0.56194976 0.31481462 0.48676362 0.7273317  0.30476594
 0.53405727 0.44139484 0.32389925 0.97901307]
(10,)


In [17]:
matrix = np.array([[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]])

print(matrix)
print(matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [33]:
v1_new = v1 + 10
v2_new = v2 + 10
matrix_new = matrix * 2
squared_v1 = np.square(v1)
squared_v2 = np.square(v2)
print(f'вектор, створений першим методом випадкових значень, зі значеннями +10: \n{np.round(v1_new,2)}')
print(f'вектор, створений другим методом випадкових значень, зі значеннями +10: \n{np.round(v2_new,2)}')
print(f'матриця зі значеннями, помноженими на 2: \n{matrix_new}')
print(f'вектор з квадратними значеннями, створений першим методом випадкових значень: \n{squared_v1}')
print(f'вектор з квадратними значеннями, створений другим методом випадкових значень: \n{squared_v2}')

вектор, створений першим методом випадкових значень, зі значеннями +10: 
[10.77 10.62 10.78 10.8  10.16 10.91 10.63 10.15 10.38 10.35]
вектор, створений другим методом випадкових значень, зі значеннями +10: 
[10.09 10.56 10.31 10.49 10.73 10.3  10.53 10.44 10.32 10.98]
матриця зі значеннями, помноженими на 2: 
[[22 28 34]
 [40 46 52]
 [58 64 70]]
вектор з квадратними значеннями, створений першим методом випадкових значень: 
[0.58850097 0.37832079 0.61292592 0.6413285  0.02706544 0.83417861
 0.39418854 0.02396467 0.14188668 0.12424763]
вектор з квадратними значеннями, створений другим методом випадкових значень: 
[0.00869204 0.31578753 0.09910824 0.23693882 0.5290114  0.09288228
 0.28521717 0.1948294  0.10491072 0.95846659]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [34]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [49]:
# для того, щоб отримати матрицю розміром 2х2, потрібно помножити матрицю В(2х3) на матрицю А(3х2)
result_matrix = B @ A
print(f'результат множення матриць В та А: \n{result_matrix}')
# оскільки розмір матриці добутку 2х2, а розмір матриці С 2х1, результат їхнього множення буде матриця розміром 2х1
result_matrix @ C
print(f'результат множення матриць BA та С: \n{result_matrix @ C}')
# оскільки розмір матриці добутку 2х2, а розмір матриці Д теж 2х2, резульат їхнього множення буде теж матриця 2х2
result_matrix @ D
print(f'результат множення матриць BA та D: \n{result_matrix @ D}')
# важливо розуміти, що попри однаковий розмір матриць, перестановка матриць в множенні змінює результат їхнього добутку!
D @ result_matrix
print(f'результат множення матриць D та ВА: \n{D@result_matrix}')

результат множення матриць В та А: 
[[0.7281 0.5202]
 [0.2034 0.2846]]
результат множення матриць BA та С: 
[[0.5202]
 [0.2846]]
результат множення матриць BA та D: 
[[0.5202 0.7281]
 [0.2846 0.2034]]
результат множення матриць D та ВА: 
[[0.2034 0.2846]
 [0.7281 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [54]:
result_matrix_T = result_matrix.T
print(f'оригінальна матриця: \n{result_matrix}')
print(f'транспонована матриця: \n{result_matrix_T}')
v1_T = v1.T
print(f'оригінальний вектор: \n{v1}')
print(f'транспонований вектор: \n{v1_T}')
column_vector = np.expand_dims(v1, axis=1)
column_vector_T = column_vector.T
print(f'вектор, створений методом expand_dims: \n{column_vector}')
print(f'транспонований вектор, створений методом expand_dims: \n{column_vector_T}')

оригінальна матриця: 
[[0.7281 0.5202]
 [0.2034 0.2846]]
транспонована матриця: 
[[0.7281 0.2034]
 [0.5202 0.2846]]
оригінальний вектор: 
[0.76713817 0.61507787 0.78289585 0.80082988 0.16451576 0.91333379
 0.62784436 0.15480526 0.37667848 0.35248778]
транспонований вектор: 
[0.76713817 0.61507787 0.78289585 0.80082988 0.16451576 0.91333379
 0.62784436 0.15480526 0.37667848 0.35248778]
вектор, створений методом expand_dims: 
[[0.76713817]
 [0.61507787]
 [0.78289585]
 [0.80082988]
 [0.16451576]
 [0.91333379]
 [0.62784436]
 [0.15480526]
 [0.37667848]
 [0.35248778]]
транспонований вектор, створений методом expand_dims: 
[[0.76713817 0.61507787 0.78289585 0.80082988 0.16451576 0.91333379
  0.62784436 0.15480526 0.37667848 0.35248778]]


Транспонування вектора не вносить ніяких змін, тоді як функція numpy.expand_dims перетворює рядок вектора на двовимірну матрицю з однією колонкою. Зрештою, транспонування такої матриці повертає до двовимірної матриці з одним рядком.